### ISSUE TITLE
Cannot import mikrotik template on a new 2.4

### ISSUE THREAD

**Issue by oernii** [andyzasl/zabbix-templates#1]
I get this error: Cannot find value map "Host Status 2.0" used for item "Ping" on "Template_Mikrotik_SNMP".

**Comment by andyzasl** [comment]
I've added value mapping requirements a few time ago to README ;)
Copy: 

Host Status 2.0    
0 ⇒ Unreachable
1 ⇒ UP

Network port admin status   
1 ⇒ Enabled
2 ⇒ Disabled

Network port status 
1 ⇒ Up
2 ⇒ Down

**Comment by oernii** [comment]
thanks, didn't even know of such a zabbix feature :)
