### ISSUE TITLE
Import Template

### ISSUE THREAD

**Issue by julianobarbosa** [andyzasl/zabbix-templates#2]
On Zabbix 3.0 Import tamplate I get this error 

O arquivo XML contêm um erro fatal 41:Specification mandate value for attribute data-pjax-transient [ Line: 50 | Column: 40 ]

**Comment by Konstantin-La** [comment]
Hey. I have no problem getting to add the template to zabbix 3.0.
Refer a full error code in English.

**Comment by max-sparker** [comment]
Zabbix 3.0

Ошибка при импортировании
Детали
Создано: Группа элементов данных "CPU" в "Template_Mikrotik_SNMP".
Создано: Группа элементов данных "Flash" в "Template_Mikrotik_SNMP".
Создано: Группа элементов данных "Health" в "Template_Mikrotik_SNMP".
Создано: Группа элементов данных "License" в "Template_Mikrotik_SNMP".
Создано: Группа элементов данных "Memory" в "Template_Mikrotik_SNMP".
Создано: Группа элементов данных "Network" в "Template_Mikrotik_SNMP".
Создано: Группа элементов данных "Status" в "Template_Mikrotik_SNMP".
Создано: Группа элементов данных "Traffic" в "Template_Mikrotik_SNMP".
Не удалось найти преобразование значений "Host Status 2.0" используемое в элементе данных "Ping" на "Template_Mikrotik_SNMP".

**Comment by andyzasl** [comment]
I haven't zabbix 3.0, so can't reproduce it now.

**Comment by max-sparker** [comment]
Изначально была такая же ошибка - неправильно сохранил шаблон (скачивал с браузера через сохранить как). Потом пересохранил через Raw по этой ссылке https://raw.githubusercontent.com/andyzasl/zabbix-templates/master/mikrotik/Mikrotik_SNMP.xml и нормально импортировался.
