### ISSUE TITLE
 I'm not managing to import .

### ISSUE THREAD

**Issue by mastergloom** [andyzasl/zabbix-templates#3]
I'm not managing to import .

http://imgur.com/a/MH6Us

[http://imgur.com/JJPdH8P](url)

[http://imgur.com/NRz5SQu](url)

**Comment by andyzasl** [comment]
Translate errors to english plz

**Comment by andyzasl** [comment]
Also, about mapping, take a look into Readme. 
https://github.com/andyzasl/zabbix-templates/blob/master/README.md

**Comment by mastergloom** [comment]
I do not understand how I do it:

and few value mappings

Host Status 2.0
0 ⇒ Unreachable
1 ⇒ UP

Network port admin status
1 ⇒ Enabled
2 ⇒ Disabled

Network Port Status
1 ⇒ Up
2 ⇒ Down

-------------------------------------------

Error:

Details
Created: Application "CPU" in "Template Mikrotik SNMP."
Created: Application "Flash" in "Template_Mikrotik_SNMP".
Created: Application "Health" in "Template_Mikrotik_SNMP".
Created: Application "License" in "Template_Mikrotik_SNMP".
Created: Application "Memory" in "Template_Mikrotik_SNMP".
Created: Application "Network" in "Template_Mikrotik_SNMP".
Created: Application "Status" in "Template_Mikrotik_SNMP".
Created: Application "Traffic" in "Template_Mikrotik_SNMP".
Could not find the mapping values "Host Status 2.0" used for the item "Ping" in "Template_Mikrotik_SNMP".

**Comment by andyzasl** [comment]
you have to read docs for zabbix

**Comment by mastergloom** [comment]
To add the snmp community must create a macro {} $ SNMP_Community?
